# Site
name: "Sheeny Care"
title: "Sheeny Care"
description: "Skin Care is made easy with Sheeny Care as we help you make skincare routines understand skincare products, talk about various skin care regimen, and give you insights on beauty products and services."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-145899743-2'
disqus: 'www-sheenycare-com'
mailchimp-list: 'https://gmail.us17.list-manage.com/subscribe/post?u=50f5361ddb4ad63e8f907f2f7&amp;id=e840b1eaa7'
include: ["_pages"]
permalink: /:title/
email: sheenycare@gmail.com

# Authors
authors:
  Aayusha:
    name: Aayusha
    display_name: Aayusha
    avatar: 'assets/images/avatar.webp'
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: aayusha2055@gmail.com
    # web: https://www.wowthemes.net/donate/
    twitter: https://twitter.com/aayusha_p
    description: "I am a skin care enthusiast making my way foward to having a healthy skin and helping others by sharing what i know."

  Swikriti:
    name: Swikriti
    display_name: Swikriti    
    avatar: 'assets/images/avatar-swik.webp'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: aayusha2055@gmail.com
    # web: https://www.wowthemes.net
    twitter: https://twitter.com/aayusha_p
    description: "I am a skin care enthusiast making my way foward to having a healthy skin and helping others by sharing what i know."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
# adsense: "disabled"
# adsense-data-ad-client: "ca-pub-3412143450191416"
# adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
